vmstat per check_swapping

diff --git a/check_swapping b/check_swapping
--- a/check_swapping
+++ b/check_swapping
@@ -1,7 +1,15 @@
 #!/bin/bash
 
-SI=$(vmstat 1 3 | tail -n 1 | awk '{print $7}')
-SO=$(vmstat 1 3 | tail -n 1 | awk '{print $8}')
+#procps
+VMSTATBIN=$(which vmstat 2> /dev/null)
+if [ $? -ne 0 ];
+then
+        echo "UNKNOWN - vmstat NOT found"
+        exit 3
+fi
+
+SI=$($VMSTATBIN 1 3 | tail -n 1 | awk '{print $7}')
+SO=$($VMSTATBIN 1 3 | tail -n 1 | awk '{print $8}')
 
 if [ -z "$SO" ];
 then
